# docker-compose.yml
version: "3"

services:
  flask:
    image: kenura/soul-nest_ml_model:latest
    ports:
      - "8001:8000"

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
