# docker-compose.yml
version: "3"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    image: registry.example.com/flaskapp:latest

  nginx:
    image: nginx:latest
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask
