name: Deploy to VPS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/python/SoulNest_ML_Model && git pull origin main -v
            cd /var/www/python/SoulNest_ML_Model && python3 -m venv .venv
            cd /var/www/python/SoulNest_ML_Model && source .venv/bin/activate
            cd /var/www/python/SoulNest_ML_Model && pip install -r requirements.txt
            # systemctl restart your-flask-service
